async function main() {
  console.log('test')
}

try {
  main()
} catch (error) {
  console.error(error)
}
